### ISSUE TITLE
Installation instructions not accessible

### ISSUE THREAD

**Issue by D4N** [coolfluid/coolfluid3#268]
The wiki with the installation instructions (http://coolfluidsrv.vki.ac.be/webfiles/coolfluid3/) and the documentation is no longer accessible. All in all this project seems to be quite abandoned, is there anyone still working on this?

**Comment by barche** [comment]
Hi,

It seems the old webserver that we used to store the doxygen files has been shut down. For now, I moved the doxygen directly to the github web pages at http://coolfluid.github.io/doxygen

The project is not abandoned, but it is at the moment primarily used in the context of PhD thesis work, so there are ups and downs.

Cheers,

Bart
